version: 2
jobs:
  build:

    working_directory: ~/korki-schedule

    docker:
    - image: circleci/openjdk:8u171-jdk
      environment:
        JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1/testdb
        JDBC_DATABASE_USERNAME: root
        JDBC_DATABASE_PASSWORD: root

    - image: postgres:9.5-alpine
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: testdb

    steps:

    - checkout
    - run:
        name: Checking dependency
        command: mvn dependency:go-offline
    - run:
        name: Building package
        command: mvn package
    - run:
        name: Mowing Dockerfile file to ./target directory
        command: mv Dockerfile ./target
    - run:
        name: Moving release.sh file to ./target directory
        command: mv release.sh ./target
    - persist_to_workspace:
        root: target
        paths:
        - ./korki-1.0.jar
        - Dockerfile
        - release.sh


  deploy:
    docker:
    - image: circleci/buildpack-deps:curl

    steps:
    - attach_workspace:
        at: .
    - setup_remote_docker
    - run:
        name: Build docker image from latest .jar file
        command: docker build -t registry.heroku.com/korkischedulgeapk/web . --iidfile image.txt
    - run:
        name: Login to heroku registry
        command: docker login --username=mkucko145@gmail.com --password=${HEROKU_API_KEY} registry.heroku.com
    - run:
        name: Pushing image to heroku registry
        command: docker push registry.heroku.com/korkischedulgeapk/web
    - run:
        name: Changing mode release.sh to be executable
        command: chmod +x ./release.sh
    - run:
        name: Run bash script
        command: ./release.sh

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build