version: 2
jobs:
  build:

    working_directory: ~/korki-schedule


    docker:
    - image: circleci/openjdk:8u171-jdk
      environment:
        JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1/testdb
        JDBC_DATABASE_USERNAME: root
        JDBC_DATABASE_PASSWORD: root

    - image: postgres:9.5-alpine
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: testdb

    steps:

    - checkout

    - run: mvn dependency:go-offline
    - run: mvn package
    - run: ls
    - run: mv Dockerfile ./target
    - run: ls target
    - persist_to_workspace:
        root: target
        paths:
          - ./korki-1.0.jar
          - Dockerfile


  deploy:
    docker:
    - image: docker:dind

    steps:
    - attach_workspace:
        at: .
    - run: ls
    - run: docker build -t korkischedule
    - run: docker login --username=mkucko145@gmail.com --password=${HEROKU_API_KEY} registry.heroku.com
    - run: docker tag korkischedule registry.heroku.com/korkischedulgeapk/web
    - run: docker push registry.heroku.com/korkischedulgeapk/web


workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build