version: 2
jobs:
  build:

    working_directory: ~/korki-schedule


    docker:
    - image: circleci/openjdk:8u171-jdk
      enviroment:
        JDBC_DATABASE_URL: jdbc:postgresql://127.0.0.1/testdb
        JDBC_DATABASE_USERNAME: root
        JDBC_DATABASE_PASSWORD: root

    - image: postgres:9.5-alpine
      enviroment:
        POSTGRES_PASSWORD: root
        POSTGRES_USER: root
        POSTGRES_DB: testdb

    steps:

    - checkout

    - run: mvn dependency:go-offline
    - run: echo "$JDBC_DATABASE_URL"
    - run: mvn package

    - persist_to_workspace:
        root: target
        paths:
          - korki-1.0.jar


  deploy:
    docker:
    - image: buildpack-deps:trusty

    steps:
    - attach_workspace:
        at: ~/korki-schedule/target
    - run: ls


workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build